### ISSUE TITLE
GPS support

### ISSUE THREAD

**Issue by Gaz492** [sdr-enthusiasts/docker-adsb-ultrafeeder#27]
Any plans to support passing a GPS dongle into this?

**Comment by dziban303** [comment]
Since ultrafeeder uses [wiedehopf's fork of readsb](https://github.com/wiedehopf/readsb), I believe that's already possible by using gpsd to talk to the GPS dongle outside of docker, and using the net_connector syntax pointing to your Pi's IP.

```yml
...
    environment:
      - READSB_NET_CONNECTOR=<your Pi's IP>,2947,gpsd_in
...
```
On a bare metal system it'd point to localhost, but I don't think `localhost` will work within the container so you'll probably need to use your Pi's IP address instead.
