### ISSUE TITLE
978 to be comment out on 1090 page

### ISSUE THREAD

**Issue by hodgkiss** [sdr-enthusiasts/docker-adsb-ultrafeeder#84]
Hi

The value:
ULTRAFEEDER_CONFIG=
          _**adsb,dump978,30978,uat_in;**_
          
          It is unnecessary in the https://sdr-enthusiasts.gitbook.io/ads-b/foundations/deploy-ultrafeeder-container if you are not using 978 dumps. I would suggest it is commented out.

**Comment by kx1t** [comment]
Hi -- thanks for your suggestion!

- this is the wrong repo for this comment. Any Gitbook comments should go to the [Gitbook repo](https://github.com/sdr-enthusiasts/gitbook-adsb-guide)
- We don't want to remove this line, especially since the sample `docker-compose.yml` file already states `# Note - remove the ones you are not using / feeding`. However, I have added another comment that says that you can remove this line if you aren't using `dump978`
